#############################################################################
# Makefile for building: multimon-ng
# Generated by qmake (2.01a) (Qt 4.8.5) on: Sat Feb 13 04:11:32 2016
# Project:  multimon-ng.pro
# Template: app
# Command: /usr/lib64/qt4/bin/qmake PREFIX=/usr/local -o Makefile multimon-ng.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DMAX_VERBOSE_LEVEL=3 -DPULSE_AUDIO -DCHARSET_UTF8
CFLAGS        = -pipe -std=gnu99 -g -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -O2 -Wall -W $(DEFINES)
CXXFLAGS      = -pipe -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -O2 -Wall -W $(DEFINES)
INCPATH       = -I/usr/lib64/qt4/mkspecs/linux-g++ -I.
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-z,relro
LIBS          = $(SUBLIBS)   -lX11 -lpulse-simple -lpulse 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/lib64/qt4/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = 
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = unixinput.c \
		uart.c \
		pocsag.c \
		selcall.c \
		hdlc.c \
		demod_zvei1.c \
		demod_zvei2.c \
		demod_zvei3.c \
		demod_pzvei.c \
		demod_dzvei.c \
		demod_ccir.c \
		demod_eia.c \
		demod_eea.c \
		demod_ufsk12.c \
		demod_poc24.c \
		demod_poc12.c \
		demod_poc5.c \
		demod_hapn48.c \
		demod_fsk96.c \
		demod_dtmf.c \
		demod_clipfsk.c \
		demod_fmsfsk.c \
		demod_afsk24.c \
		demod_afsk24_3.c \
		demod_afsk24_2.c \
		demod_afsk12.c \
		demod_flex.c \
		BCHCode.c \
		costabi.c \
		costabf.c \
		clip.c \
		fms.c \
		demod_eas.c \
		demod_morse.c \
		demod_dumpcsv.c \
		xdisplay.c \
		demod_display.c 
OBJECTS       = unixinput.o \
		uart.o \
		pocsag.o \
		selcall.o \
		hdlc.o \
		demod_zvei1.o \
		demod_zvei2.o \
		demod_zvei3.o \
		demod_pzvei.o \
		demod_dzvei.o \
		demod_ccir.o \
		demod_eia.o \
		demod_eea.o \
		demod_ufsk12.o \
		demod_poc24.o \
		demod_poc12.o \
		demod_poc5.o \
		demod_hapn48.o \
		demod_fsk96.o \
		demod_dtmf.o \
		demod_clipfsk.o \
		demod_fmsfsk.o \
		demod_afsk24.o \
		demod_afsk24_3.o \
		demod_afsk24_2.o \
		demod_afsk12.o \
		demod_flex.o \
		BCHCode.o \
		costabi.o \
		costabf.o \
		clip.o \
		fms.o \
		demod_eas.o \
		demod_morse.o \
		demod_dumpcsv.o \
		xdisplay.o \
		demod_display.o
DIST          = /usr/lib64/qt4/mkspecs/common/unix.conf \
		/usr/lib64/qt4/mkspecs/common/linux.conf \
		/usr/lib64/qt4/mkspecs/common/gcc-base.conf \
		/usr/lib64/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/lib64/qt4/mkspecs/common/g++-base.conf \
		/usr/lib64/qt4/mkspecs/common/g++-unix.conf \
		/usr/lib64/qt4/mkspecs/qconfig.pri \
		/usr/lib64/qt4/mkspecs/features/qt_functions.prf \
		/usr/lib64/qt4/mkspecs/features/qt_config.prf \
		/usr/lib64/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/lib64/qt4/mkspecs/features/default_pre.prf \
		/usr/lib64/qt4/mkspecs/features/release.prf \
		/usr/lib64/qt4/mkspecs/features/default_post.prf \
		/usr/lib64/qt4/mkspecs/features/shared.prf \
		/usr/lib64/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/lib64/qt4/mkspecs/features/warn_on.prf \
		/usr/lib64/qt4/mkspecs/features/resources.prf \
		/usr/lib64/qt4/mkspecs/features/uic.prf \
		/usr/lib64/qt4/mkspecs/features/yacc.prf \
		/usr/lib64/qt4/mkspecs/features/lex.prf \
		/usr/lib64/qt4/mkspecs/features/include_source_dir.prf \
		multimon-ng.pro
QMAKE_TARGET  = multimon-ng
DESTDIR       = 
TARGET        = multimon-ng

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: multimon-ng.pro  /usr/lib64/qt4/mkspecs/linux-g++/qmake.conf /usr/lib64/qt4/mkspecs/common/unix.conf \
		/usr/lib64/qt4/mkspecs/common/linux.conf \
		/usr/lib64/qt4/mkspecs/common/gcc-base.conf \
		/usr/lib64/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/lib64/qt4/mkspecs/common/g++-base.conf \
		/usr/lib64/qt4/mkspecs/common/g++-unix.conf \
		/usr/lib64/qt4/mkspecs/qconfig.pri \
		/usr/lib64/qt4/mkspecs/features/qt_functions.prf \
		/usr/lib64/qt4/mkspecs/features/qt_config.prf \
		/usr/lib64/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/lib64/qt4/mkspecs/features/default_pre.prf \
		/usr/lib64/qt4/mkspecs/features/release.prf \
		/usr/lib64/qt4/mkspecs/features/default_post.prf \
		/usr/lib64/qt4/mkspecs/features/shared.prf \
		/usr/lib64/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/lib64/qt4/mkspecs/features/warn_on.prf \
		/usr/lib64/qt4/mkspecs/features/resources.prf \
		/usr/lib64/qt4/mkspecs/features/uic.prf \
		/usr/lib64/qt4/mkspecs/features/yacc.prf \
		/usr/lib64/qt4/mkspecs/features/lex.prf \
		/usr/lib64/qt4/mkspecs/features/include_source_dir.prf
	$(QMAKE) PREFIX=/usr/local -o Makefile multimon-ng.pro
/usr/lib64/qt4/mkspecs/common/unix.conf:
/usr/lib64/qt4/mkspecs/common/linux.conf:
/usr/lib64/qt4/mkspecs/common/gcc-base.conf:
/usr/lib64/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/lib64/qt4/mkspecs/common/g++-base.conf:
/usr/lib64/qt4/mkspecs/common/g++-unix.conf:
/usr/lib64/qt4/mkspecs/qconfig.pri:
/usr/lib64/qt4/mkspecs/features/qt_functions.prf:
/usr/lib64/qt4/mkspecs/features/qt_config.prf:
/usr/lib64/qt4/mkspecs/features/exclusive_builds.prf:
/usr/lib64/qt4/mkspecs/features/default_pre.prf:
/usr/lib64/qt4/mkspecs/features/release.prf:
/usr/lib64/qt4/mkspecs/features/default_post.prf:
/usr/lib64/qt4/mkspecs/features/shared.prf:
/usr/lib64/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/lib64/qt4/mkspecs/features/warn_on.prf:
/usr/lib64/qt4/mkspecs/features/resources.prf:
/usr/lib64/qt4/mkspecs/features/uic.prf:
/usr/lib64/qt4/mkspecs/features/yacc.prf:
/usr/lib64/qt4/mkspecs/features/lex.prf:
/usr/lib64/qt4/mkspecs/features/include_source_dir.prf:
qmake:  FORCE
	@$(QMAKE) PREFIX=/usr/local -o Makefile multimon-ng.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/multimon-ng1.0.0 || $(MKDIR) .tmp/multimon-ng1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/multimon-ng1.0.0/ && (cd `dirname .tmp/multimon-ng1.0.0` && $(TAR) multimon-ng1.0.0.tar multimon-ng1.0.0 && $(COMPRESS) multimon-ng1.0.0.tar) && $(MOVE) `dirname .tmp/multimon-ng1.0.0`/multimon-ng1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/multimon-ng1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

unixinput.o: unixinput.c multimon.h \
		msvc_support.h \
		win32_getopt.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o unixinput.o unixinput.c

uart.o: uart.c multimon.h \
		msvc_support.h \
		win32_getopt.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o uart.o uart.c

pocsag.o: pocsag.c multimon.h \
		msvc_support.h \
		win32_getopt.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o pocsag.o pocsag.c

selcall.o: selcall.c multimon.h \
		msvc_support.h \
		win32_getopt.h \
		filter.h \
		filter-i386.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o selcall.o selcall.c

hdlc.o: hdlc.c multimon.h \
		msvc_support.h \
		win32_getopt.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o hdlc.o hdlc.c

demod_zvei1.o: demod_zvei1.c multimon.h \
		msvc_support.h \
		win32_getopt.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o demod_zvei1.o demod_zvei1.c

demod_zvei2.o: demod_zvei2.c multimon.h \
		msvc_support.h \
		win32_getopt.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o demod_zvei2.o demod_zvei2.c

demod_zvei3.o: demod_zvei3.c multimon.h \
		msvc_support.h \
		win32_getopt.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o demod_zvei3.o demod_zvei3.c

demod_pzvei.o: demod_pzvei.c multimon.h \
		msvc_support.h \
		win32_getopt.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o demod_pzvei.o demod_pzvei.c

demod_dzvei.o: demod_dzvei.c multimon.h \
		msvc_support.h \
		win32_getopt.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o demod_dzvei.o demod_dzvei.c

demod_ccir.o: demod_ccir.c multimon.h \
		msvc_support.h \
		win32_getopt.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o demod_ccir.o demod_ccir.c

demod_eia.o: demod_eia.c multimon.h \
		msvc_support.h \
		win32_getopt.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o demod_eia.o demod_eia.c

demod_eea.o: demod_eea.c multimon.h \
		msvc_support.h \
		win32_getopt.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o demod_eea.o demod_eea.c

demod_ufsk12.o: demod_ufsk12.c multimon.h \
		msvc_support.h \
		win32_getopt.h \
		filter.h \
		filter-i386.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o demod_ufsk12.o demod_ufsk12.c

demod_poc24.o: demod_poc24.c multimon.h \
		msvc_support.h \
		win32_getopt.h \
		filter.h \
		filter-i386.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o demod_poc24.o demod_poc24.c

demod_poc12.o: demod_poc12.c multimon.h \
		msvc_support.h \
		win32_getopt.h \
		filter.h \
		filter-i386.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o demod_poc12.o demod_poc12.c

demod_poc5.o: demod_poc5.c multimon.h \
		msvc_support.h \
		win32_getopt.h \
		filter.h \
		filter-i386.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o demod_poc5.o demod_poc5.c

demod_hapn48.o: demod_hapn48.c multimon.h \
		msvc_support.h \
		win32_getopt.h \
		filter.h \
		filter-i386.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o demod_hapn48.o demod_hapn48.c

demod_fsk96.o: demod_fsk96.c multimon.h \
		msvc_support.h \
		win32_getopt.h \
		filter.h \
		filter-i386.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o demod_fsk96.o demod_fsk96.c

demod_dtmf.o: demod_dtmf.c multimon.h \
		msvc_support.h \
		win32_getopt.h \
		filter.h \
		filter-i386.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o demod_dtmf.o demod_dtmf.c

demod_clipfsk.o: demod_clipfsk.c multimon.h \
		msvc_support.h \
		win32_getopt.h \
		filter.h \
		filter-i386.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o demod_clipfsk.o demod_clipfsk.c

demod_fmsfsk.o: demod_fmsfsk.c multimon.h \
		msvc_support.h \
		win32_getopt.h \
		filter.h \
		filter-i386.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o demod_fmsfsk.o demod_fmsfsk.c

demod_afsk24.o: demod_afsk24.c multimon.h \
		msvc_support.h \
		win32_getopt.h \
		filter.h \
		filter-i386.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o demod_afsk24.o demod_afsk24.c

demod_afsk24_3.o: demod_afsk24_3.c multimon.h \
		msvc_support.h \
		win32_getopt.h \
		filter.h \
		filter-i386.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o demod_afsk24_3.o demod_afsk24_3.c

demod_afsk24_2.o: demod_afsk24_2.c multimon.h \
		msvc_support.h \
		win32_getopt.h \
		filter.h \
		filter-i386.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o demod_afsk24_2.o demod_afsk24_2.c

demod_afsk12.o: demod_afsk12.c multimon.h \
		msvc_support.h \
		win32_getopt.h \
		filter.h \
		filter-i386.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o demod_afsk12.o demod_afsk12.c

demod_flex.o: demod_flex.c multimon.h \
		msvc_support.h \
		win32_getopt.h \
		filter.h \
		filter-i386.h \
		BCHCode.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o demod_flex.o demod_flex.c

BCHCode.o: BCHCode.c BCHCode.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o BCHCode.o BCHCode.c

costabi.o: costabi.c 
	$(CC) -c $(CFLAGS) $(INCPATH) -o costabi.o costabi.c

costabf.o: costabf.c 
	$(CC) -c $(CFLAGS) $(INCPATH) -o costabf.o costabf.c

clip.o: clip.c multimon.h \
		msvc_support.h \
		win32_getopt.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o clip.o clip.c

fms.o: fms.c multimon.h \
		msvc_support.h \
		win32_getopt.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o fms.o fms.c

demod_eas.o: demod_eas.c multimon.h \
		msvc_support.h \
		win32_getopt.h \
		filter.h \
		filter-i386.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o demod_eas.o demod_eas.c

demod_morse.o: demod_morse.c multimon.h \
		msvc_support.h \
		win32_getopt.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o demod_morse.o demod_morse.c

demod_dumpcsv.o: demod_dumpcsv.c multimon.h \
		msvc_support.h \
		win32_getopt.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o demod_dumpcsv.o demod_dumpcsv.c

xdisplay.o: xdisplay.c multimon.h \
		msvc_support.h \
		win32_getopt.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o xdisplay.o xdisplay.c

demod_display.o: demod_display.c multimon.h \
		msvc_support.h \
		win32_getopt.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o demod_display.o demod_display.c

####### Install

install_target: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/usr/local/bin/ || $(MKDIR) $(INSTALL_ROOT)/usr/local/bin/ 
	-$(INSTALL_PROGRAM) "$(QMAKE_TARGET)" "$(INSTALL_ROOT)/usr/local/bin/$(QMAKE_TARGET)"

uninstall_target:  FORCE
	-$(DEL_FILE) "$(INSTALL_ROOT)/usr/local/bin/$(QMAKE_TARGET)"
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/local/bin/ 


install:  install_target  FORCE

uninstall: uninstall_target   FORCE

FORCE:

